---
engines:
  csslint:
    enabled: true
    checks:
      compatible-vendor-prefixes:
        enabled: false
      box-sizing:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    exclude_fingerprints:
    - d71c866dcb8d670c5e540a820329340c
    checks:
      no-alert:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.js"
exclude_paths: ['App/scripts/tests']
